import type { Metadata } from "next";

import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";

import Providers from "./providers";
// import { Theme } from "@radix-ui/themes";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const space = Space_Grotesk({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${space.className} dark:text-white bg-gradient-to-r from-violet200 to-pink200 dark:bg-gradient-to-b dark:from-darkMode dark:to-darkMode
         text-gray-950 relative min-h-screen container max-w-4xl mx-auto`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
